/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ethanyang.project_1;

import java.awt.Component;
import java.awt.Toolkit;
import java.sql.Date;
import javax.swing.*;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.JPanel;

/**
 *
 * @author yangyifan
 */
public class Backup extends javax.swing.JFrame {
    private final java.awt.Color btnSelected = new java.awt.Color(65, 211, 189);
    private final java.awt.Color btnNotSelected = new java.awt.Color(108, 73, 184);
    private static java.text.SimpleDateFormat time = new java.text.SimpleDateFormat("HH:mm:ss");

    /**
     * Creates new form Menu
     */
    public Backup() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        sideBar = new javax.swing.JPanel();
        btn_tools = new javax.swing.JPanel();
        tlsbtn_icon = new javax.swing.JLabel();
        tlsbtn_text = new javax.swing.JLabel();
        btn_settings = new javax.swing.JPanel();
        setbtn_icon = new javax.swing.JLabel();
        setbtn_text = new javax.swing.JLabel();
        btn_schedule = new javax.swing.JPanel();
        schbtn_icon = new javax.swing.JLabel();
        schbtn_text = new javax.swing.JLabel();
        btn_dashboard = new javax.swing.JPanel();
        dabtn_icon = new javax.swing.JLabel();
        dabtn_text = new javax.swing.JLabel();
        main_panel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(100, 238, 238));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sideBar.setBackground(new java.awt.Color(108, 73, 184));
        sideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_tools.setBackground(new java.awt.Color(108, 73, 184));
        btn_tools.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_toolsMouseClicked(evt);
            }
        });

        tlsbtn_icon.setForeground(new java.awt.Color(204, 102, 0));
        tlsbtn_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tlsbtn_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-toolbox_25.png"))); // NOI18N
        tlsbtn_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tlsbtn_iconMouseClicked(evt);
            }
        });

        tlsbtn_text.setFont(new java.awt.Font("Hannotate TC", 1, 20)); // NOI18N
        tlsbtn_text.setForeground(new java.awt.Color(255, 255, 255));
        tlsbtn_text.setText("Tools");
        tlsbtn_text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tlsbtn_textMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btn_toolsLayout = new javax.swing.GroupLayout(btn_tools);
        btn_tools.setLayout(btn_toolsLayout);
        btn_toolsLayout
                .setHorizontalGroup(btn_toolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(btn_toolsLayout.createSequentialGroup().addGap(34, 34, 34)
                                .addComponent(tlsbtn_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 43,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34).addComponent(tlsbtn_text, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(68, Short.MAX_VALUE)));
        btn_toolsLayout.setVerticalGroup(btn_toolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(tlsbtn_icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                        Short.MAX_VALUE)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                        btn_toolsLayout.createSequentialGroup().addContainerGap()
                                .addComponent(tlsbtn_text, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                .addContainerGap()));

        sideBar.add(btn_tools, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 290, -1));

        btn_settings.setBackground(new java.awt.Color(108, 73, 184));
        btn_settings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_settingsMouseClicked(evt);
            }
        });

        setbtn_icon.setForeground(new java.awt.Color(204, 102, 0));
        setbtn_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        setbtn_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-settings_25.png"))); // NOI18N
        setbtn_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setbtn_iconMouseClicked(evt);
            }
        });

        setbtn_text.setFont(new java.awt.Font("Hannotate TC", 1, 20)); // NOI18N
        setbtn_text.setForeground(new java.awt.Color(255, 255, 255));
        setbtn_text.setText("Settings");
        setbtn_text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setbtn_textMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btn_settingsLayout = new javax.swing.GroupLayout(btn_settings);
        btn_settings.setLayout(btn_settingsLayout);
        btn_settingsLayout
                .setHorizontalGroup(btn_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(btn_settingsLayout.createSequentialGroup().addGap(34, 34, 34)
                                .addComponent(setbtn_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 43,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29).addComponent(setbtn_text, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(68, Short.MAX_VALUE)));
        btn_settingsLayout.setVerticalGroup(btn_settingsLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(setbtn_icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                        Short.MAX_VALUE)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                        btn_settingsLayout.createSequentialGroup().addContainerGap()
                                .addComponent(setbtn_text, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                .addContainerGap()));

        sideBar.add(btn_settings, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 290, -1));

        btn_schedule.setBackground(new java.awt.Color(108, 73, 184));
        btn_schedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_scheduleMouseClicked(evt);
            }
        });

        schbtn_icon.setForeground(new java.awt.Color(204, 102, 0));
        schbtn_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        schbtn_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-schedule_25.png"))); // NOI18N
        schbtn_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                schbtn_iconMouseClicked(evt);
            }
        });

        schbtn_text.setFont(new java.awt.Font("Hannotate TC", 1, 20)); // NOI18N
        schbtn_text.setForeground(new java.awt.Color(255, 255, 255));
        schbtn_text.setText("Schedule");
        schbtn_text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                schbtn_textMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btn_scheduleLayout = new javax.swing.GroupLayout(btn_schedule);
        btn_schedule.setLayout(btn_scheduleLayout);
        btn_scheduleLayout
                .setHorizontalGroup(btn_scheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(btn_scheduleLayout.createSequentialGroup().addGap(34, 34, 34)
                                .addComponent(schbtn_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 43,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29).addComponent(schbtn_text, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(68, Short.MAX_VALUE)));
        btn_scheduleLayout.setVerticalGroup(btn_scheduleLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(schbtn_icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                        Short.MAX_VALUE)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                        btn_scheduleLayout.createSequentialGroup().addContainerGap()
                                .addComponent(schbtn_text, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                .addContainerGap()));

        sideBar.add(btn_schedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 290, -1));

        btn_dashboard.setBackground(new java.awt.Color(65, 211, 189));
        btn_dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_dashboardMouseClicked(evt);
            }
        });

        dabtn_icon.setForeground(new java.awt.Color(204, 102, 0));
        dabtn_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dabtn_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-a_home_25.png"))); // NOI18N
        dabtn_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dabtn_iconMouseClicked(evt);
            }
        });

        dabtn_text.setFont(new java.awt.Font("Hannotate TC", 1, 20)); // NOI18N
        dabtn_text.setForeground(new java.awt.Color(255, 255, 255));
        dabtn_text.setText("Dashboard");
        dabtn_text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dabtn_textMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btn_dashboardLayout = new javax.swing.GroupLayout(btn_dashboard);
        btn_dashboard.setLayout(btn_dashboardLayout);
        btn_dashboardLayout
                .setHorizontalGroup(btn_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(btn_dashboardLayout.createSequentialGroup().addGap(34, 34, 34)
                                .addComponent(dabtn_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 43,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29).addComponent(dabtn_text, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(68, Short.MAX_VALUE)));
        btn_dashboardLayout.setVerticalGroup(btn_dashboardLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(dabtn_icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                        Short.MAX_VALUE)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                        btn_dashboardLayout.createSequentialGroup().addContainerGap()
                                .addComponent(dabtn_text, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                .addContainerGap()));

        sideBar.add(btn_dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 290, -1));

        background.add(sideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 601));

        dashboardCreate();

        /**
         * Adding component panel to the main_panel
         * 
         * 
         */
        addToMainPanel(p_dashboard);

        /**
         * Adding the main_panel to the background
         * 
         * 
         */
        background.add(main_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 690, 600));

        /**
         * set the Conent Container to add background to the frame
         * 
         * 
         */
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(background,
                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(background,
                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        pack();
        setCenter(this);
        NewThread timeRefreshThread = new NewThread("TimeRefresh");
    }// </editor-fold>//GEN-END:initComponents

    private void initMyThings() {

    }

    private void dashboardCreate() {
        p_dashboard = new javax.swing.JPanel();
        da_time_p = new javax.swing.JPanel();
        da_ti_disp = new javax.swing.JLabel();
        da_nextclass = new javax.swing.JPanel();
        nclass_text = new javax.swing.JLabel();
        nclass_name = new javax.swing.JLabel();
        nclass_duration = new javax.swing.JLabel();
        p_dashboard.setBackground(new java.awt.Color(79, 176, 198));
        p_dashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        da_time_p.setBackground(new java.awt.Color(140, 215, 144));

        da_ti_disp.setFont(new java.awt.Font("Monaco", 0, 130)); // NOI18N
        da_ti_disp.setText("Loading...");

        javax.swing.GroupLayout da_time_pLayout = new javax.swing.GroupLayout(da_time_p);
        da_time_p.setLayout(da_time_pLayout);
        da_time_pLayout
                .setHorizontalGroup(
                        da_time_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(da_time_pLayout.createSequentialGroup().addGap(34, 34, 34)
                                        .addComponent(da_ti_disp, javax.swing.GroupLayout.PREFERRED_SIZE, 626,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(30, Short.MAX_VALUE)));
        da_time_pLayout.setVerticalGroup(da_time_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(da_time_pLayout
                        .createSequentialGroup().addGap(30, 30, 30).addComponent(da_ti_disp,
                                javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(30, Short.MAX_VALUE)));

        p_dashboard.add(da_time_p, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        da_nextclass.setBackground(new java.awt.Color(215, 255, 241));

        nclass_text.setFont(new java.awt.Font("Luminari", 1, 30)); // NOI18N
        nclass_text.setText("Next Scheduled Class");

        nclass_name.setFont(new java.awt.Font("Bangla MN", 1, 150)); // NOI18N
        nclass_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nclass_name.setText("Null");

        nclass_duration.setFont(new java.awt.Font("Luminari", 0, 30)); // NOI18N
        nclass_duration.setText("Null");

        javax.swing.GroupLayout da_nextclassLayout = new javax.swing.GroupLayout(da_nextclass);
        da_nextclass.setLayout(da_nextclassLayout);
        da_nextclassLayout.setHorizontalGroup(da_nextclassLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(da_nextclassLayout.createSequentialGroup().addContainerGap().addGroup(da_nextclassLayout
                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(da_nextclassLayout.createSequentialGroup().addGap(6, 6, 6)
                                .addComponent(nclass_name, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                        .addGroup(da_nextclassLayout.createSequentialGroup()
                                .addComponent(nclass_text, javax.swing.GroupLayout.PREFERRED_SIZE, 325,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138,
                                        Short.MAX_VALUE)
                                .addComponent(nclass_duration, javax.swing.GroupLayout.PREFERRED_SIZE, 207,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)))));
        da_nextclassLayout.setVerticalGroup(da_nextclassLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(da_nextclassLayout.createSequentialGroup().addGap(16, 16, 16)
                        .addGroup(da_nextclassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(nclass_text, javax.swing.GroupLayout.PREFERRED_SIZE, 62,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nclass_duration, javax.swing.GroupLayout.PREFERRED_SIZE, 43,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nclass_name, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap()));

        p_dashboard.add(da_nextclass, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 690, 310));

    }

    private void dashboardDispose() {
        p_dashboard.setEnabled(false);
        p_dashboard.setVisible(false);
    }

    private void dashboardDisplay() {
        p_dashboard.setEnabled(true);
        p_dashboard.setVisible(true);
    }

    private void settingsCreate() {
        p_settings = new JPanel();

    }

    private void settingsDispose() {
        p_settings.setEnabled(false);
        p_settings.setVisible(false);
    }

    private void settingsDisplay() {
        p_settings.setEnabled(true);
        p_settings.setVisible(true);
    }

    private void scheduleCreate() {
        p_schedule = new JPanel();

    }

    private void scheduleDispose() {
        p_schedule.setEnabled(false);
        p_schedule.setVisible(false);
    }

    private void scheduleDisplay() {
        p_schedule.setEnabled(true);
        p_schedule.setVisible(true);
    }

    private void toolsCreate() {
        p_tools = new JPanel();
    }

    private void toolsDispose() {
        p_tools.setEnabled(false);
        p_tools.setVisible(false);
    }

    private void toolsDisplay() {
        p_tools.setEnabled(true);
        p_tools.setVisible(true);
    }

    public static void setCenter(javax.swing.JFrame window) {
        int windowWidth = window.getWidth();
        int windowHeight = window.getHeight();
        java.awt.Toolkit kit = java.awt.Toolkit.getDefaultToolkit();
        java.awt.Dimension screenSize = kit.getScreenSize();
        int screenWidth = screenSize.width;
        int screenHeight = screenSize.height;
        window.setLocation((screenWidth - windowWidth) / 2, (screenHeight - windowHeight) / 2);
    }

    public static void timeDisplay() {

        while (true) {
            try {// try...catch...保护程序健康运行
                Thread.sleep(100);
                // 线程暂停1000ms
                // 为防止内存占用，每隔一秒更新一次
            } catch (InterruptedException e1) {
                e1.printStackTrace();
            }
            // 将时间标签信息设置为实时获取的时间
            da_ti_disp.setText(time.format(new java.util.Date()));
            // 下课播报功能，请谨慎使用看人下菜，见风使舵方能使得万年船
            /*
             * if (classOverNotify) { if (inList(dates[3].getText(), notifications)) {
             * System.out.println("Notifying..."); Warning classOver = new Warning("下课小精灵",
             * "老师，您辛苦了！同学们提醒您：下课时间到了！您该去休息啦！谢谢老师您的付出！我们饶过彼此可好？", "好的，我马上下课", "OK, 我现在下课");
             * classOver.yes.addActionListener(new ActionListener() {
             * 
             * @Override public void actionPerformed(ActionEvent e) { classOver.close(); }
             * }); } }
             */
        }
    }

    /**
     * add a component to the main panel
     * 
     * used to switch between functions
     * 
     * @param component
     */
    private void addToMainPanel(Component component) {
        javax.swing.GroupLayout main_panelLayout = new javax.swing.GroupLayout(main_panel);
        main_panel.setLayout(main_panelLayout);
        main_panelLayout.setHorizontalGroup(main_panelLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 690, Short.MAX_VALUE)
                .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(main_panelLayout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(component, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))));
        main_panelLayout
                .setVerticalGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 601, Short.MAX_VALUE)
                        .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(main_panelLayout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(component, javax.swing.GroupLayout.PREFERRED_SIZE, 601,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))));
    }

    /**
     * Add main_panel to Background Panel
     */
    private void addMainPanelToBG() {
        background.add(main_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 690, 600));
    }

    /**
     * add all things to the Frame
     */
    private void addAllToFrame() {
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(background,
                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(background,
                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
    }

    /**
     * Integrated Operation to switch between panels
     */
    private void switchTo(Component clickedPanel) {
        addToMainPanel(clickedPanel);
        addMainPanelToBG();
        addAllToFrame();
    }

    // Dashboard Methods:

    /**
     * This Method is the method called when the Dashboard button in the sideBar is
     * clicked
     */
    private void dashboardClicked() {
        dashboardDisplay();
        // switchTo(p_dashboard);
        btn_settings.setBackground(btnNotSelected);
        btn_schedule.setBackground(btnNotSelected);
        btn_tools.setBackground(btnNotSelected);
        btn_dashboard.setBackground(btnSelected);
    }

    /**
     * Dashboard
     * 
     * icon part
     * 
     * @param evt
     */
    private void dabtn_iconMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_dabtn_iconMouseClicked
        dashboardClicked();
    }// GEN-LAST:event_dabtn_iconMouseClicked

    /**
     * Dashboard
     * 
     * text part
     * 
     * @param evt
     */
    private void dabtn_textMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_dabtn_textMouseClicked
        dashboardClicked();
    }// GEN-LAST:event_dabtn_textMouseClicked

    /**
     * Dashboard
     * 
     * Panel part
     * 
     * @param evt
     */
    private void btn_dashboardMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btn_dashboardMouseClicked
        dashboardClicked();

    }// GEN-LAST:event_btn_dashboardMouseClicked

    // Schedule Methods:

    /**
     * This Method is the method called when the Schedule button in the sideBar is
     * clicked
     */
    private void scheduleClicked() {
        btn_settings.setBackground(btnNotSelected);
        btn_schedule.setBackground(btnSelected);
        btn_tools.setBackground(btnNotSelected);
        btn_dashboard.setBackground(btnNotSelected);
        dashboardDispose();
    }

    /**
     * Schedule
     * 
     * icon part
     * 
     * @param evt
     */
    private void schbtn_iconMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_schbtn_iconMouseClicked
        scheduleClicked();
    }// GEN-LAST:event_schbtn_iconMouseClicked

    /**
     * Schedule
     * 
     * text part
     * 
     * @param evt
     */
    private void schbtn_textMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_schbtn_textMouseClicked
        scheduleClicked();
    }// GEN-LAST:event_schbtn_textMouseClicked

    /**
     * Schedule
     * 
     * Panel part
     * 
     * @param evt
     */
    private void btn_scheduleMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btn_scheduleMouseClicked
        scheduleClicked();
    }// GEN-LAST:event_btn_scheduleMouseClicked

    // Settings Method:

    /**
     * This Method is the method called when the Schedule button in the sideBar is
     * clicked
     */
    private void settingsClicked() {
        btn_schedule.setBackground(btnNotSelected);
        btn_tools.setBackground(btnNotSelected);
        btn_dashboard.setBackground(btnNotSelected);
        btn_settings.setBackground(btnSelected);
    }

    /**
     * Settings
     * 
     * text part
     * 
     * @param evt
     */
    private void setbtn_textMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_setbtn_textMouseClicked
        settingsClicked();
    }// GEN-LAST:event_setbtn_textMouseClicked

    /**
     * Settings
     * 
     * Panel part
     * 
     * @param evt
     */
    private void btn_settingsMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btn_settingsMouseClicked
        settingsClicked();
    }// GEN-LAST:event_btn_settingsMouseClicked

    /**
     * Settings
     * 
     * icon part
     * 
     * @param evt
     */
    private void setbtn_iconMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_setbtn_iconMouseClicked
        settingsClicked();
    }// GEN-LAST:event_setbtn_iconMouseClicked

    // Tools Method:

    /**
     * This Method is the method called when the Schedule button in the sideBar is
     * clicked
     */
    private void toolsClicked() {
        btn_settings.setBackground(btnNotSelected);
        btn_schedule.setBackground(btnNotSelected);
        btn_tools.setBackground(btnSelected);
        btn_dashboard.setBackground(btnNotSelected);
    }

    /**
     * Tools
     * 
     * Panel part
     * 
     * @param evt
     */
    private void btn_toolsMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btn_toolsMouseClicked
        toolsClicked();
    }// GEN-LAST:event_btn_toolsMouseClicked

    /**
     * Tools
     * 
     * text part
     * 
     * @param evt
     */
    private void tlsbtn_textMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_tlsbtn_textMouseClicked
        toolsClicked();
    }// GEN-LAST:event_tlsbtn_textMouseClicked

    /**
     * Tools
     * 
     * icon part
     * 
     * @param evt
     */
    private void tlsbtn_iconMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_tlsbtn_iconMouseClicked
        toolsClicked();
    }// GEN-LAST:event_tlsbtn_iconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            Menu window = new Menu();
            window.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel btn_dashboard;
    private javax.swing.JPanel btn_schedule;
    private javax.swing.JPanel btn_settings;
    private javax.swing.JPanel btn_tools;
    private javax.swing.JPanel da_nextclass;
    private static javax.swing.JLabel da_ti_disp;
    private javax.swing.JPanel da_time_p;
    private javax.swing.JLabel dabtn_icon;
    private javax.swing.JLabel dabtn_text;
    private javax.swing.JPanel main_panel;
    private javax.swing.JLabel nclass_duration;
    private javax.swing.JLabel nclass_name;
    private javax.swing.JLabel nclass_text;
    private javax.swing.JPanel p_dashboard;
    private javax.swing.JLabel schbtn_icon;
    private javax.swing.JLabel schbtn_text;
    private javax.swing.JLabel setbtn_icon;
    private javax.swing.JLabel setbtn_text;
    private javax.swing.JPanel sideBar;
    private javax.swing.JLabel tlsbtn_icon;
    private javax.swing.JLabel tlsbtn_text;
    private javax.swing.JPanel p_settings;
    private javax.swing.JPanel p_schedule;
    private javax.swing.JPanel p_tools;
    // End of variables declaration//GEN-END:variables
}